[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_PROXY = "https://todo-list-demo-e11643ecaddb.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 