[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_PROXY = "https://todo-list-demo-e11643ecaddb.herokuapp.com"

# SPA 라우팅을 위한 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 