[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_PROXY = "https://todo-list-demo-e11643ecaddb.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "https://todo-list-demo-e11643ecaddb.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 